<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>rEFIndConfigEditor</RootNamespace>
    <AssemblyName>rEFIndConfigEditor</AssemblyName>
    <Platforms>AnyCPU;x64;x86;ARM64</Platforms>
    <ApplicationIcon>../.resources/icon/refind.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <VersionContents>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)..\.version\version').Trim())</VersionContents>
    <Version>$(VersionContents)</Version>
    <AssemblyVersion>$(VersionContents).0</AssemblyVersion>
    <FileVersion>$(VersionContents).0</FileVersion>
    <InformationalVersion>$(VersionContents)</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../.resources/icon/refind.ico" Link="refind.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../.resources/icon/refind256.png" Link="refind256.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../.resources/data/themes.json" Link="themes/themes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../.resources/themes/previews/*.png" Link="themes/previews/%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
